"""ATT&CK Navigator layer export for vex investigation results.

Serializes ATTACKMapping objects into a MITRE ATT&CK Navigator v4.5 compatible
JSON layer that can be opened at https://mitre-attack.github.io/attack-navigator/

Typical usage::

    vex investigate evil.com --navigator > layer.json
    # Then open layer.json in ATT&CK Navigator
"""

from __future__ import annotations

import json
from typing import Optional, Union

from ..models import ATTACKMapping, InvestigateResult, TriageResult
from .. import __version__

# Mapping from vex tactic names (Title Case) to Navigator tactic IDs (lowercase hyphenated)
_TACTIC_NORMALIZE: dict[str, str] = {
    "Execution": "execution",
    "Persistence": "persistence",
    "Privilege Escalation": "privilege-escalation",
    "Defense Evasion": "defense-evasion",
    "Credential Access": "credential-access",
    "Discovery": "discovery",
    "Lateral Movement": "lateral-movement",
    "Collection": "collection",
    "Command and Control": "command-and-control",
    "Exfiltration": "exfiltration",
    "Impact": "impact",
    "Initial Access": "initial-access",
    "Reconnaissance": "reconnaissance",
    "Resource Development": "resource-development",
}


def to_navigator_layer(
    results: Union[
        InvestigateResult,
        list[InvestigateResult],
        TriageResult,
        list[TriageResult],
    ],
    *,
    title: Optional[str] = None,
    ioc: Optional[str] = None,
) -> str:
    """Build an ATT&CK Navigator v4.5 JSON layer from vex results.

    Collects all ATTACKMapping objects from InvestigateResult(s), deduplicates
    by technique_id (first occurrence wins), and serializes to Navigator JSON.

    TriageResult has no attack_mappings — if only triage results are passed,
    the layer will have zero techniques (but is still valid JSON).

    Args:
        results: One or more InvestigateResult or TriageResult objects.
        title:   Optional layer title. Defaults to "vex — {ioc}".
        ioc:     Optional IOC string for metadata/title. Auto-detected if not given.

    Returns:
        JSON string — write to a file or pipe to stdout.
    """
    # Normalise to list
    if not isinstance(results, list):
        results = [results]

    # Collect all ATTACKMapping objects from InvestigateResults
    mappings: list[ATTACKMapping] = []
    for r in results:
        if isinstance(r, InvestigateResult):
            mappings.extend(r.attack_mappings)

    # Deduplicate by technique_id (keep first occurrence)
    seen: set[str] = set()
    unique: list[ATTACKMapping] = []
    for m in mappings:
        if m.technique_id not in seen:
            seen.add(m.technique_id)
            unique.append(m)

    # Build techniques array
    techniques = []
    for m in unique:
        tactic_norm = _TACTIC_NORMALIZE.get(
            m.tactic,
            m.tactic.lower().replace(" ", "-"),
        )
        comment = ""
        if m.evidence:
            comment = m.evidence[:200]  # Navigator truncates long comments
        techniques.append({
            "techniqueID": m.technique_id,
            "tactic": tactic_norm,
            "score": 100,
            "color": "",
            "comment": comment,
            "enabled": True,
            "metadata": [],
            "links": [],
            "showSubtechniques": True,
        })

    # Determine IOC string for metadata
    if not ioc:
        first = results[0]
        if isinstance(first, InvestigateResult):
            ioc = first.triage.ioc
        elif isinstance(first, TriageResult):
            ioc = first.ioc
        else:
            ioc = ""

    layer = {
        "name": title or f"vex — {ioc}",
        "versions": {
            "attack": "14",
            "navigator": "4.9",
            "layer": "4.5",
        },
        "domain": "enterprise-attack",
        "description": f"Generated by vex v{__version__} from IOC investigation of {ioc}",
        "techniques": techniques,
        "gradient": {
            "colors": ["#ffffff", "#ff6666"],
            "minValue": 0,
            "maxValue": 100,
        },
        "legendItems": [],
        "metadata": [
            {"name": "generated_by", "value": f"vex v{__version__}"},
            {"name": "ioc", "value": ioc or ""},
        ],
        "showTacticRowBackground": True,
        "tacticRowBackground": "#dddddd",
        "hideDisabled": False,
    }

    return json.dumps(layer, indent=2, ensure_ascii=False)
